## 一. Basic Operations 基本操作

在 matlab 中，%是注释符号。基础的数学运算有以下这些：

```
1 + 2   %加
5 - 6   %减
7 * 4   %乘
9 / 3   %除
6 ^ 4   %幂指数
log(20) %对数运算
exp(30) %指数运算
abs(-2) %绝对值运算

```



逻辑运算：




```

1 == 2             %判断是否相等
ans = 0            %false
--------------------------------------------------------------------------------------------
1 ~= 2             % ~= 是 ！= 的意思，判断是否不相等
ans = 1            %True 
--------------------------------------------------------------------------------------------
1 && 0             %逻辑 AND （和运算）
ans = 0
--------------------------------------------------------------------------------------------
1 || 0             %逻辑 OR（或运算）
ans = 1            
--------------------------------------------------------------------------------------------
xor(1,0)           %异或运算
ans = 1 
--------------------------------------------------------------------------------------------

```


更换行首提示符

```

PS1('>>');   %单引号内就是待替换的行首提示符

```

变量赋值：

```

a = 3        % 赋值数字
a = 3；      % 假如不想让其输出可以在后面加上分号（；）
b = 'Hello world'；   %赋值字符串
--------------------------------------------------------------------------------------------
disp(a)
disp(sprintf('2 decimals :%0.2f',a))   %sprintf打印格式化字符串
--------------------------------------------------------------------------------------------
format long   % 让接下来的字符串显示默认的位数
a

format short  % 让接下来的字符串小数点后面打印少量的位数
a
--------------------------------------------------------------------------------------------

```


向量和矩阵：


```

A = [1 2;3 4;5 6;] %创建矩阵变量，分号的意思就是换行到下一行
A =

   1   2
   3   4
   5   6
 
B = [1 2 3]  %创建向量
B =

   1   2   3
--------------------------------------------------------------------------------------------

v = 1:0.1:2    % a:x:b 表示[a,b]区间，x表示递增步长
v =
    1.0000    1.1000    1.2000    1.3000    1.4000    1.5000    1.6000    1.7000    1.8000    1.9000    2.0000

--------------------------------------------------------------------------------------------

ones(2,3)   %生成2*3的元素都为1的矩阵
ans =
     1     1     1
     1     1     1

%如果想生成2*3的元素都为2的矩阵，当然不是用 twos(2,3),而是用下面的方式

2*ones(2,3)
ans =

   2   2   2
   2   2   2
   
%与 ones 相同的快捷命令是 zeros
--------------------------------------------------------------------------------------------

zeros(1,3)  %生成1*3的零矩阵
ans =
     0     0     0
--------------------------------------------------------------------------------------------     

rand(1,3)  %生成1*3的随机数矩阵
ans =

   0.960762   0.089159   0.384507
--------------------------------------------------------------------------------------------   
eye(2,3)   % 生成2*3的单位矩阵
ans =
     1     0     0
     0     1     0
--------------------------------------------------------------------------------------------     
eye(3)     % 生成3*3的单位矩阵
ans =
     1     0     0
     0     1     0
     0     0     1
--------------------------------------------------------------------------------------------

```

帮助函数：

```

help eye  % help 后面跟一个命令名字，就会显示出这个命令的详细用法


```

## 二. Moving Data Around

矩阵计算：


```

A = [1,2; 3,4; 5,6;];
size(A)           %计算矩阵的维度大小
ans =
     3     2
--------------------------------------------------------------------------------------------

size(A,1)         %显示该矩阵的行数，1代表返回行数
ans =
     3
size(A,2)         %显示该矩阵的列数，2代表返回列数
ans =
     2
--------------------------------------------------------------------------------------------

v = [1,2,3,4]; 
length(v)         % 计算向量的最大维度的大小，length 通常对向量使用，而不对矩阵使用
ans =
     4

--------------------------------------------------------------------------------------------


```



读取和存储文件数据：


```

load xxx               %xxx为当前路径下的文件名
load ('xxx')           %以字符串的形式加载
v = xxx(1:10)          %建立向量v，元素分别为xxx文件内1~10的数据

--------------------------------------------------------------------------------------------

save xxx.mat V         %将当前的数据存储存储到文件中，并且变量名为 V
save xxx.txt V -ascii  %将当前的数据存储存储到ascii编码的文本文档中

```

显示命令：


```

pwd              %显示当前路径
ls               %显示当前路径的文件夹
cd 'path'        %打开该路径
who              %在当前内存中存储的所有变量
whos             %更详细地显示变量的名称、维度和占用多少内存空间和数据类型
clear            %清除所有变量
addpath('path')  %将路径添加到当前搜索处


```

矩阵索引操作：


```

A = [1,2; 3,4; 5,6;];

A(3,2)   %索引矩阵第1行第2列的元素
ans =
     6
--------------------------------------------------------------------------------------------

A(2,:)   %索引矩阵第2行所有元素,冒号表示该行或者该列的所有元素
ans =
     3     4
A(:,2)   %索引矩阵第2列所有元素
ans =
     2
     4
     6
--------------------------------------------------------------------------------------------

A([1 3],:)  %索引矩阵第1行和第3行所有元素
ans =
     1     2
     5     6
--------------------------------------------------------------------------------------------
A(:,2) = [10;11;12]  %将A的第二列用右边的向量替代
ans =
     1     10
     3     11
     5     12
--------------------------------------------------------------------------------------------

A = [A,[100;101;102]] %加入一列新的向量
A =
     1     2     100
     3     4     101
     5     6     102
--------------------------------------------------------------------------------------------
          
A(:)    %将矩阵A的元素变成列向量
ans =
     1
     3
     5
     2
     4
     6
     100
     101
     102
     
--------------------------------------------------------------------------------------------

A = [1,2;3,4];           %合并矩阵，A在左边，B在右边
B = [4,5;6,7];
C = [A B]                %等价于 C = [A,B]
C =
     1     2     4     5
     3     4     6     7
     
C = [A;B]                %合并矩阵，A在上边，B在下边
C =
     1     2
     3     4
     4     5
     6     7     
  
--------------------------------------------------------------------------------------------


```



## 三. Computing on Data

## 四. Plotting Data

## 五. Control Statements: for, while, if statement

## 六. Vectorization